name: pre-commit

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --config .pre-commit-config.yaml --all-files
